config/routes.rb
JobsJugaad::Application.routes.draw do

  resources :job_seekers, :controller => "job_seekers", :except => [:new]
  controller 'job_seekers' do
    get "profile" => :profile
    get "register" => :new
    get "remove_photo" => :remove_photo
  end
  resources :employers, :controller => "employers", :except => [:new]
  controller 'employers' do
    get "elogin" => :login
    get "eregister" => :new
    get "eprofile" => :profile
    get "add_job" => :add_job
    get "remove_photo_emp" => :remove_photo
  end
  resources :jobs
  controller :jobs do
    get "view_applicants" => :view_applicants
    post "search_results" => :search_results
    get "search_results" => :search_results
    post "apply" => :apply
  end
  resources :sessions, :except => [:destroy]
  controller :sessions do
    get "logout" => :destroy
    post "login" => :login
    post "eregister" => :register
    post "register" => :register
    get "change_password" => :change_password
    post "update_password" => :update_password
    get "forgot_password" => :forgot_password
    post "reset_password" => :reset_password
    get "set_new_password" => :set_new_password
    get "reset_user_password" => :reset_user_password
    get "activate_user" => :activate_user
    post "set_new_password" => :set_new_password
    post "save_new_password" => :save_new_password
  end

  root :to => 'home#index'

end

app/models/job_seeker.rb
class JobSeeker < ActiveRecord::Base
  attr_accessible :name, :email, :gender, :date_of_birth, 
                  :password, :password_confirmation, :auth_token,
                  :location, :mobile_number, :key_skills, :experience, 
                  :industry, :photo, :resume, :activated, :password_reset_token

  has_many :job_applications
  has_many :jobs, :through => :job_applications
  has_many :skills, :as => :key_skill, :dependent => :destroy
  # accepts_nested_attributes_for :skills, :allow_destroy => true

  has_attached_file :resume
  validates :resume_file_name, :allow_blank => true, :format => {
    :with => %r{[.](pdf|docx|doc|txt)$}i, 
    :message => "Invalid Resume Format: Allowed Formats Are Only in PDF, DOCx, Doc and Text"
  }
  
  has_attached_file :photo, :styles => { :small => "175x175>"}, 
  :default_url => '/assets/default-photo/default.gif'

  validates_attachment_size :photo, :less_than => 6.megabytes
  validates_format_of :photo, :with => %r{\.(jpg|jpeg|png|ico|gif)}i, 
  :message => "Invalid Image: Allowed Formats Are Only in jpeg, jpg, png, ico and gif"
  
  
  has_secure_password
  validates :name, :presence  => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :confirmation => true, :presence => true, :if => :password
  validates :password_confirmation, :presence => true, :if => :password 
  validates :password, :length => { :minimum => 6 }, :if => :password
  
  validates_format_of :email,
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
    :message => "Doesn't Looks the correct email ID"


  validates :mobile_number, 
            :numericality => { :only_integer => true }, 
            :length => { :is => 10 }, 
            :allow_blank => true

  validates :gender, :presence => true

  def key_skills
    self.get_skill_set
    # self.skills.collect(&:name).join(", ")
  end

  def key_skills=(skill_arr)
    self.set_skill_set(skill_arr)
    # skill_arr.split(",").each do |skill|
    #   self.skills.build(:name => skill)
    # end
    # # new_skillset = skill_arr.split(",").each { |word| word.strip! }
    # # old_skillset = self.skills.collect(&:name)
    # # median_skillset = new_skillset & old_skillset
    # # skills_to_be_deleted = old_skillset - median_skillset
    # # skill_to_be_added = new_skillset - median_skillset
    # # skills_to_be_deleted.each do |skill|
    # #   self.skills.find_by_name(skill).delete
    # # end
    # # skill_to_be_added.each do |skill|
    # #   self.skills.find_or_initialize_by_name(:name => skill)
    # # end
  end

  def industry_options
    JobSeeker::INDUSTRY
  end

  INDUSTRY = {
    "IT" => "IT",
    "Audit" => "Audit",
    "Accounting" => "Accounting",
    "Administration" => "Administration",
    "Advertising" => "Advertising",
    "Entertainment" => "Entertainment",
    "Travel" => "Travel",
    "Top Management" => "Top Management",
    "Charted Accounting" => "Charted Accounting",
    "Others" => "Others"
  }

  EXPERIENCE = {
    "Fresher" => "fresher",
    "0"  => "0",
    "1"  => "1",
    "2"  => "2",
    "3"  => "3",
    "4"  => "4",
    "5"  => "5",
    "6"  => "6",
    "7"  => "7",
    "8"  => "8",
    "9"  => "9",
    "10" => "10",
    "10+" => "10+"
  }
end

app/controllers/job_seekers_controller.rb
class JobSeekersController < ApplicationController
  
  before_filter :is_valid_access?, :except => [:new, :forgot_password]
  # before_filter :is_authorised_access?, :on => [:edit]

  def is_authorised_access?
    if params[:id] == session[:id]
      render "edit"
    else
      redirect_to request.referrer, :notice => "You are not authorised to edit this profile"
    end
  end

  def is_valid_access?
    if session[:id].nil? 
      redirect_to root_path , :notice => "You are not currently logged into the system..."      
    else
      if session['user_type'] == 'employer'
        unless employer_authorised_to_see_profile?
          redirect_to request.referrer, :notice => "You are not allowed to see this particular profile"
        end
      end
    end
  end

  def employer_authorised_to_see_profile?
    authorized_ids = get_authorized_ids
    @employer = Employer.find(session[:id])
    @employer.jobs.each do |job|
      authorized_ids.concat(job.job_seekers.collect(&:id))
    end

    if(authorized_ids.include?(Integer(params["id"])))
      return true
    else 
      return false
    end
  end

  def get_authorized_ids
    authorized_ids = []
    @employer = Employer.find(session[:id])
    @employer.jobs.each do |job|
      authorized_ids.concat(job.job_seekers.collect(&:id))
    end
    authorized_ids
  end

  def index
  end

  def show
    @job_seeker = JobSeeker.find(params[:id])
  end

  def edit
    if params[:id].to_s == session[:id].to_s
      @job_seeker = JobSeeker.find(params[:id])
      @job_seeker.key_skills
    else
      redirect_to :profile, :notice => "You are not authorised to edit this profile"
    end
  end

  def update
    @job_seeker = JobSeeker.find(params[:id])
    
    respond_to do |format|
      if @job_seeker.update_attributes(params[:job_seeker])
        format.html { redirect_to profile_path, notice: 'Your profile has been successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def remove_photo
    @job_seeker = JobSeeker.find(session[:id])
    @job_seeker.photo.destroy
    @job_seeker.update_attribute(:photo, nil)
    redirect_to profile_path
  end

  def new
    @job_seeker = JobSeeker.new
  end

  def profile
    @job_seeker = JobSeeker.find(session[:id])
  end
end

app/helpers/job_seekers_helper.rb
module JobSeekersHelper
  def get_skills(user)
    skill_set = ""
    user.skills.each do |skill|
      skill_set += skill.name
      skill_set += ", "
    end
    skill_set
  end
end

app/views/job_seekers/_form.html.erb
<%= form_for(@job_seeker) do |post_form| %>
  <% if @job_seeker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_seeker.errors.count, "error") %> prohibited the details from being saved:</h2>
    </div>
  <% end %>
  
  <fieldset><legend>Editing Profile</legend>
  <div id="form">
      <table id="edit_table" border="2">
        <tr>
          <td><%= post_form.label :name %></td>
          <td><%= post_form.text_field :name %></td>
            <% str = "" %>
            <% unless @job_seeker.errors[:name].empty? %>
              <% @job_seeker.errors[:name].each { |msg| str+=msg+", " }%>
              <td class="error_notice"><%= str %></td>
            <% end %>
        </tr>
        <tr>
          <td><%= post_form.label :email %></td>
          <td><%= post_form.text_field :email %></td>
          <% str = "" %>
            <% unless @job_seeker.errors[:email].empty? %>
              <% @job_seeker.errors[:email].each { |msg| str+=msg+", " } %>
                <td class="error_notice"><%= str %></td>
            <% end %>
          </tr>
        <tr>
          <td><%= post_form.label :location %></td>
          <td><%= post_form.text_field :location %></td>
        </tr>
        <tr>
          <td><%= post_form.label :mobile_number %></td>
          <td><%= post_form.text_field :mobile_number %></td>
          <% unless error_present?(:mobile_number, @job_seeker) %>
            <td class="error-notice"><%= get_errors(:mobile_number, @job_seeker) %></td>
          <% end %>
        </tr>
        <tr>
          <td><%= post_form.label :experience %> (in years):</td>
          <td><%= post_form.text_field :experience %></td>
        </tr>
        <tr>
          <td><%= post_form.label :industry %></td>
          <td><%= post_form.text_field :industry %></td>
        </tr>
        <tr>
          <td><%= post_form.label :key_skills %></td>
          <td><%= post_form.text_field :key_skills %></td>
        </tr>
        <tr>
          <td><%= post_form.submit "Update Profile" %></td>
        </tr>
      </table>
    <%= link_to 'Back to Profile', profile_path %>
  </div>
  </fieldset>
<% end %>

app/views/job_seekers/_login.html.erb
<div id="login">
  <% if notice %>
    <div id="notice"><p><%= notice %></p></div>
  <% end %>
  <h2>Login to get started....</h2>
    <%= form_tag(:controller => "sessions", :action => "login") do %>
      <table>
        <tr>
          <td><%= label_tag :email, "Enter Email" %></td>
          <td><%= email_field_tag :email, nil, :placeholder => "Enter Email" %></td>
        </tr>
        <tr>
          <td><%= label_tag :password, "Enter Password" %></td>
          <td><%= password_field_tag :password, nil, :placeholder => "Enter Password" %></td>
        </tr>
        <tr>
          <td><%= hidden_field_tag :user_type, "job_seeker" %></td>
        </tr>
        <tr>
          <td></td><td><%= submit_tag "Login" %></td>
        </tr>
      </table>
    <% end %>
<%= link_to "Forgot Password?", forgot_password_path(:user => "JobSeeker") %> <br />
<%= link_to 'Login As Employer', elogin_path %><br />
<%= link_to 'New Job Seeker', register_path %>
</div>

app/views/job_seekers/edit.html.erb
<%= form_for(@job_seeker, :html => { :multipart => true }) do |post_form| %>
  <% if @job_seeker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_seeker.errors.count, "error") %> prohibited the details from being saved:</h2>
    </div>
  <% end %>
  <fieldset><legend>Editing Profile</legend>
  <div id="form">
    <table id="edit_table">
      <tr>
        <td><%= post_form.label :name %></td>
        <td><%= post_form.text_field :name %></td>
          <% unless error_present?(:name, @job_seeker) %>
            <td class="error_notice"><%= get_errors(:name, @job_seeker) %></td>
          <% end %>
      </tr>
      <tr>
        <td><%= post_form.label :gender %></td>
        <td><%= post_form.select :gender, [["Male","Male"], ["Female", "Female"], ["Others", "Others"]]%></td>
        <% unless error_present?(:gender, @job_seeker) %>
            <td class="error_notice"><%= get_errors(:gender, @job_seeker) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= post_form.label :date_of_birth %></td>
        <td><%= post_form.date_select :date_of_birth, :start_year => 1962, :end_year => Time.now.year - 16, :order => [:day, :month, :year] %></td>
      </tr>
      <tr>
        <td><%= post_form.label :email %></td>
        <td><%= @job_seeker.email %></td>
          <% unless error_present?(:email, @job_seeker) %>
              <td class="error_notice"><%= get_errors(:email, @job_seeker) %></td>
          <% end %>
        </tr>
      <tr>
        <td><%= post_form.label :location %></td>
        <td><%= post_form.text_field :location %></td>
      </tr>
      <tr>
        <td><%= post_form.label :mobile_number %></td>
        <td><%= post_form.text_field :mobile_number %></td>
        <% unless error_present?(:mobile_number, @job_seeker) %>
          <td class="error_notice"><%= get_errors(:mobile_number, @job_seeker) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= post_form.label :experience %> (in years):</td>
        <td><%= post_form.text_field :experience %></td>
      </tr>
      <tr>
        <td><%= post_form.label :industry %></td>
        <td><%= post_form.text_field :industry %></td>
      </tr>
      <tr>
        <td><%= post_form.label :key_skills %></td>
        <td><%= post_form.text_field :key_skills %></td>
      </tr>
      <tr>
        <td>Profile Image: </td>
        <td><%= post_form.file_field :photo %></td>
        <% unless error_present?(:photo, @job_seeker) %>
          <td class="error_notice"><%= get_errors(:photo, @job_seeker) %></td>
        <% end %>
      </tr>
      <tr>
        <td>Resume: </td>
        <td><%= post_form.file_field :resume %></td>
        <% unless error_present?(:resume_file_name, @job_seeker) %>
          <td class="error_notice"><%= get_errors(:resume_file_name, @job_seeker) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= post_form.submit "Update Profile" %></td>
      </tr>
    </table>
    <%= link_to 'Back to Profile', profile_path %>
  </div>
  </fieldset>
<% end %>

app/views/job_seekers/new.html.erb
<%= form_for(@job_seeker, :url => '/register' ) do |f| %>
  <% if @job_seeker.errors.any? %>
    <div class="error_messages">
     <h2><%= pluralize(@job_seeker.errors.count, "error") %> prohibited the details from being saved:</h2>
    </div>
  <% end %>
  <fieldset>
    <legend>Registration</legend>
    <table>
      <%= hidden_field_tag :user_type, "job_seeker" %>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
      <% unless error_present?(:name, @job_seeker) %>
        <td class="error-notice"><%= get_errors(:name, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.email_field :email %></td>
      <% unless error_present?(:email, @job_seeker) %>
        <td class="error-notice"><%= get_errors(:email, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password %></td>
      <% unless error_present?(:password, @job_seeker) %>
        <td class="error-notice"><%= get_errors(:password, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :password_confirmation %></td>
      <td><%= f.password_field :password_confirmation %></td>
      <% unless error_present?(:password_confirmation, @job_seeker) %>
        <td class="error-notice"><%= get_errors(:password_confirmation, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :gender %></td>
      <td><%= f.select :gender, [["Male","Male"], ["Female", "Female"], ["Others", "Others"]], :prompt => "Select Gender" %></td>
      <% unless error_present?(:gender, @job_seeker) %>
        <td class="error-notice"><%= get_errors(:gender, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :date_of_birth %></td>
      <td><%= f.date_select :date_of_birth, :start_year => 1962, :end_year => Time.now.year - 16, :order => [:day, :month, :year] %></td>
    </tr>
    <tr>
      <td><%= f.label :location %> (City in India)</td>
      <td><%= f.text_field :location %></td>
      <% unless error_present?(:location, @job_seeker) %>
        <td><%= get_errors(:location, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td><%= f.label :mobile_number %></td>
      <td><%= f.telephone_field :mobile_number %></td>
      <% unless error_present?(:mobile_number, @job_seeker) %>
        <td class="error-notice"><%= get_errors(:mobile_number, @job_seeker) %></td>
      <% end %>
    </tr>
    <tr>
      <td>Profile Details</td>
    </tr>
    <tr>
      <td><%= f.label :experience %></td>
      <td><%= f.select "experience", JobSeeker::EXPERIENCE %> years</td>
    </tr>
    <tr>
      <td><%= f.label :key_skills %></td>
      <td><%= f.text_field :key_skills %></td>
    </tr>
    <tr>
      <td><%= f.label :industry %></td>
      <td><%= f.select :industry, JobSeeker::INDUSTRY %></td>
    </tr>
    <tr>
      <td></td>
      <td><p class="button"><%= f.submit %></p></td>
    </tr>
  </fieldset>
<% end %>

app/views/job_seekers/profile.html.erb
<% if session[:id].nil? || session['user_type'] != 'job_seeker' %>
  <center> 
    <div id = "not_login">
    <p>
      You are not currently logged into the system...
      <br />Please click <%= link_to 'here', root_path %> to login
     </p>
    </div>
  </center> 
<% else %>
  <div id = "main-container">
    <h3> Welcome <%= @job_seeker.name %></h3>
    <fieldset id="profile-info" class="profile-fieldset">
      <legend id="profile-info-legend">Your Profile Information</legend>
      <% unless notice.nil? %>
        <div id = "notice"> <%= notice %> </div>
      <% end %>
      <div id="profile-container">
        <div id="links_to_use">
          <%= link_to 'Change Password', change_password_path %> |
          <%= link_to 'Edit', edit_job_seeker_path(@job_seeker) %> 
        </div>
        <div id = "profile_div">
          <h5> Your Profile Information : </h5>
          <div id = "profile-image">
           <%= image_tag @job_seeker.photo.url(:small) %>
            <ul>
              <li><%= link_to 'Change Image', "" %></li>
              <li><%= link_to 'Remove Image', remove_photo_path %></li>
              <li><%= link_to 'View Resume', @job_seeker.resume.url %></li>
            </ul>
          </div>
          <div id="profile_table">
            <table>
              <tr><td> Name: </td><td><%= @job_seeker.name %></td></tr>
              <tr><td> Email: </td><td><%= @job_seeker.email %></td></tr>
              <tr><td> Date Of Birth: </td><td><%= @job_seeker.date_of_birth.strftime("%d-%m-%Y") %></td></tr>
              <tr><td> Gender: </td><td><%= @job_seeker.gender %></td></tr>
              <tr><td> Location: </td><td><%= @job_seeker.location %></td></tr>
              <tr><td> Mobile Number: </td><td><%= @job_seeker.mobile_number %></td></tr>
              <tr><td> Experience : </td>
                  <td>
                    <% if @job_seeker.experience.match(/Fresher/i) %>
                      <%= @job_seeker.experience %>
                    <% else %>
                      <%= @job_seeker.experience %> years
                    <% end %>
                </td></tr>
              <tr><td> Industry : </td>
                <td>
                  <% if @job_seeker.industry.nil? %>
                      Not Mentioned
                  <% else %>
                      <%= @job_seeker.industry %>
                  <% end %>
                </td>
              </tr>
              <tr><td> Key Skills : </td>
                <td>
                  <% if @job_seeker.skills.nil? %>
                      Not Mentioned
                  <% else %>
                      <%= @job_seeker.key_skills %>
                  <% end %>
                </td>
            </table>
          </div>
        </div>
      </div>
    </fieldset>
    <fieldset class="profile-fieldset">
      <legend id="jobs-applied-legend">Your Job Applications</legend>
      <div id="applied-jobs-container">
        <table>
          <% current_user.jobs.each do |job| %>
            <tr><td> Job <%= current_user.jobs.index(job) + 1 %></td></tr>
            <tr><td> Job Title : </td><td> <%= link_to job.title, job %></td></tr>
            <tr><td> Employer </td><td><%= link_to job.employer.name, job.employer, :target => '_blank' %></td></tr>
            <tr><td> Job Description </td><td><%= job.description %> </td></tr>
            <tr><td> Location </td><td><%= job.location %> </td></tr>
            
          <% end %>
        </table>
      </div>
    </fieldset>
    <fieldset class="profile-fieldset"><legend>Search and Apply for Jobs:</legend>
      <%= form_tag(:controller => "jobs", :action => 'search_results') do %>
        <%= text_field_tag :location, nil, :placeholder => "Search by Location" %>
        <%= hidden_field_tag :search_type, "location" %>
        <%= submit_tag "Search By Location" %>
      <% end %>
    </fieldset>
  </div>
<% end %>

app/views/job_seekers/show.html.erb
<div id = "main-container">
  <fieldset id="profile-info" class="profile-fieldset">
    <div id="profile-container">
      <div id = "profile_div">
        <h5> Profile Information of <%= @job_seeker.name %>: </h5>
        <div id = "profile-image">
         <%= image_tag @job_seeker.photo.url(:small) %>
        </div>
        <div id="profile_table">
          <table>
            <tr><td> Name: </td><td><%= @job_seeker.name %></td></tr>
            <tr><td> Email: </td><td><%= @job_seeker.email %></td></tr>
            <tr><td> Location: </td><td><%= @job_seeker.location %></td></tr>
            <tr><td> Mobile Number: </td><td><%= @job_seeker.mobile_number %></td></tr>
            <tr><td> Experience : </td>
                <td>
                  <% if @job_seeker.experience.nil? %>
                      Not Mentioned
                  <% else %>
                      <%= @job_seeker.experience %> years
                  <% end %>
              </td></tr>
            <tr><td> Industry : </td>
              <td>
                <% if @job_seeker.industry.nil? %>
                    Not Mentioned
                <% else %>
                    <%= @job_seeker.industry %>
                <% end %>
              </td>
            </tr>
            <tr><td> Key Skills : </td>
              <td>
                <% if @job_seeker.skills.nil? %>
                    Not Mentioned
                <% else %>
                    <%= @job_seeker.key_skills %>
                <% end %>
              </td>
          </table>
        </div>
      </div>
      <%= link_to 'Call Candidate for interview', "" %> | 
      <%= link_to 'Reject Candidate', "" %> | 
      <%= link_to 'Back to applicants', request.referer%>
    </div>
  </fieldset>
</div>