config/routes.rb
JobsJugaad::Application.routes.draw do

  resources :job_seekers, :controller => "job_seekers", :except => [:new]
  controller 'job_seekers' do
    get "profile" => :profile
    get "register" => :new
    get "remove_photo" => :remove_photo
  end
  resources :employers, :controller => "employers", :except => [:new]
  controller 'employers' do
    get "elogin" => :login
    get "eregister" => :new
    get "eprofile" => :profile
    get "add_job" => :add_job
    get "remove_photo_emp" => :remove_photo
  end
  resources :jobs
  controller :jobs do
    get "view_applicants" => :view_applicants
    post "search_results" => :search_results
    get "search_results" => :search_results
    post "apply" => :apply
  end
  resources :sessions, :except => [:destroy]
  controller :sessions do
    get "logout" => :destroy
    post "login" => :login
    post "eregister" => :register
    post "register" => :register
    get "change_password" => :change_password
    post "update_password" => :update_password
    get "forgot_password" => :forgot_password
    post "reset_password" => :reset_password
    get "set_new_password" => :set_new_password
    get "reset_user_password" => :reset_user_password
    get "activate_user" => :activate_user
    post "set_new_password" => :set_new_password
    post "save_new_password" => :save_new_password
  end

  root :to => 'home#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :title, :description, :location, :skill_set, :salary_min, 
                  :salary_max, :salary_type, :key_skills
  belongs_to :employer
  has_many :job_applications
  has_many :job_seekers, :through => :job_applications
  has_many :skills, :as => :key_skill, :dependent => :destroy

  validates :description, :presence => true, :length => { :minimum => 50 }
  validates :location, :presence => true
    # validate do |job|
    #   job.errors.add_to_base("Important...if you have confusion, simply enter 0") if job.salary_min.blank?
    # end
  validates_presence_of :salary_min, :message => "Important...if you have confusion, simply enter 0"
  validates_presence_of :salary_max, :message => "It is Important to enter Maximum Salary"
  validates_presence_of :salary_type, :message => "Please Enter the Salary Type in either LPA or pm"
  validates :salary_min, :numericality => true
  validates :salary_max, :numericality => true

  scope :location, lambda { |place| where("location = ?", place)}
  scope :skill, lambda { |skill| where("name")}
  
  def key_skills
    get_skill_set
  end

  def key_skills=(skill_arr)
    set_skill_set(skill_arr)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def create
    @employer = Employer.find(session[:id])
    @job = @employer.jobs.build(params[:job])
    respond_to do |format|
      if @job.save
        format.html { redirect_to :eprofile, :notice => "A new job has been posted successfully" }
      else
        format.html { render :template => "employers/add_job.html.erb", :notice => "Job Could not be saved" }
      end
    end
  end

  def edit
    begin
      @job = Job.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to :root, :notice => "Not Authorised to view this page"
    end
  end

  def view_applicants
    @job = Job.find(params[:id])
  end

  def show
    begin
      @job = Job.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to :root, :notice => "Not Authorised to view this page"
    end
  end

  def authorized_ids(job_seeker)
    job_seeker.jobs.collect(&:id)
  end

  def apply
    if session[:id].nil?
      redirect_to :root, :notice => "Please Login or Register as the job seeker"
    else
      if session[:user_type] == "employer"
        redirect_to :root, :notice => "You are Logged in as employer. Please login as the Job Seeker"
      else
        @job_seeker = JobSeeker.find(session[:id])
        authorized_ids = authorized_ids(@job_seeker)
        if authorized_ids.include?(Integer(params[:job_id]))
          redirect_to :profile, :notice => "You have already applied for this job"
        else
          @job_seeker.jobs << Job.find(params[:job_id])
          redirect_to :profile, :notice => "You have successfully applied to this job"
        end
      end
    end
  end

  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to :eprofile, notice: "Job was successfully updated." }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def search_results
    case params[:search_type]
    when "location"
      @jobs = Job.includes(:skills).location(params[:location]).page(params[:page]).per(10)
    when "skills"
      job_arr = []
      skill_set = Skill.skill_name(params[:skills]).skill_type("Job")
      skill_set.each do |job|
        job_arr << job.key_skill
      end
      @jobs = Kaminari.paginate_array(job_arr).page(params[:page]).per(10)
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to request.referer, :notice => "Job has been successfully removed" }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_search_jobs_form.html.erb
<h1> Search Your Dream Jobs Here .... </h1>
<div id="search">
  <%= form_tag(:controller => "jobs", :action => 'search_results') do %>
    <%= text_field_tag :location, nil, :placeholder => "Search by Location" %>
    <%= hidden_field_tag :search_type, "location" %>
    <%= submit_tag "Search By Location" %>
  <% end %>

  <%= form_tag(:controller => "jobs", :action => 'search_results') do %>
    <%= text_field_tag :skills, nil, :placeholder => "Search by Skills" %>
    <%= hidden_field_tag :search_type, "skills" %>
    <%= submit_tag "Search By Skills" %>
  <% end %>
</div>

app/views/jobs/apply.html.erb
<h1>You can apply for jobs here </h1>

app/views/jobs/edit.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
    </div>
  <% end %>

  <fieldset>
    <legend>Enter Job Details</legend>
    <table>
      <tr>
        <td><%= f.label :title %></td>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <td><%= f.label :description %></td>
        <td><%= f.text_area :description %></td>
        <% unless error_present?(:description, @job) %>
          <td class="error_notice"><%= get_errors(:description, @job) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= f.label :location %></td>
        <td><%= f.text_field :location %></td>
        <% unless error_present?(:location, @job) %>
        <td class="error_notice"><%= get_errors(:location, @job) %></td>
        <% end %>
      </tr>

      <tr>
        <td><%= f.label "Salary Offered" %></td>
        <td>
          <%= f.text_field :salary_min, :class => "salary-fields", :placeholder => "Minimum Salary" %> to 
          <%= f.text_field :salary_max, :class => "salary-fields", :placeholder => "Maximum Salary" %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :salary_type %></td>
        <td><%= f.select :salary_type, [["LPA", "LPA"], ["pm", "pm"]] %></td>
      </tr>
      <tr>
        <td><%= f.label :key_skills %></td>
        <td><%= f.text_field :key_skills %></td>
      <tr>
        <td><%= f.submit %></td>
      </tr>
    </table>
    <%= link_to 'Back to profile', eprofile_path %>
  </fieldset>

<% end %>

app/views/jobs/search.html.erb
<% @jobs.each do |job| %>
  <%= job %>
<% end %>

app/views/jobs/search_results.html.erb
<h3> Your Search Results </h3>
<% if @jobs.empty? %>
  <center> 
    <div id="no-jobs">
      <p> No Jobs Found..try something different..<br />Click <%= link_to "here", request.referer %> to go back </p>
    </div>
  </center>
<% else %>
  <center>
  <table id = "job-listings" border="2">
    <% @jobs.each do |job| %>
        <tr class="<%= cycle('job_posting_odd', 'job_posting_even') %>">
          <td>
            <ul>
              <%= form_for( job, :url => { :action => :apply, :job_id => job.id }, :method => :post ) do |f| %>
                <li><div class="desc-placeholder">Job Title: </div><%= link_to job.title, job, :target => "_blank" %></li>
                <li><div class="desc-placeholder">Employer : </div><%= link_to job.employer.name, job.employer, :target => "_blank" %></li>
                <li><div class="desc-placeholder">Job Description : </div><%= job.description.gsub("\r\n", "<br />").html_safe %></li>
                <li><div class="desc-placeholder">Location : </div><%= job.location %></li>
                <li><div class="desc-placeholder">Key Skills Required: </div><%= job.skills.collect(&:name).join(", ") %></li>
                <li><div class="desc-placeholder">Salary Offered: </div>
                  <%= job.salary_min %> to <%= job.salary_max %> <%= job.salary_type %>
                </li>
              <%= submit_tag "Apply to Job" %>
              <% end %>
            </ul>
          </td>
        </tr> 
    <% end %>
  </center>
  <%= paginate @jobs %>
<% end %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<fieldset>
  <legend>Job Description</legend>
  <table>
    <tr>
      <td>Employer: </td>
      <td><%= link_to @job.employer.name, @job.employer %></td>
    </tr>
    <tr>
      <td>Description:</td>
      <td><%= @job.description %></td>
    </tr>
    <tr>
      <td>Location</td>
      <td><%= @job.location %></td>
    </tr>
    <tr>
      <td>Salary Offered</td>
      <td>&#8377; <%= @job.salary_min %> to <%= @job.salary_max %> <%= @job.salary_type %></td>
    </tr>
    <tr>
      <td> Skills Required : </td>
      <td> <%= @job.key_skills %></td>
    </tr>
    <% if session[:user_id] == "employer" && session[:id] == @job.employer.id %>
      <%= link_to "Edit", edit_job %>
    <% end %>
  </table>
</fieldset>

app/views/jobs/view_applicants.html.erb
<fieldset>
  <legend>The following are the job applicants for the selected Job </legend>
  <% if @job.job_seekers.empty? %>
    <div id="no-job-seekers">
      There are no job seekers yet!!!
    </div>
  <% else %>
  <table>
    <tr>
      <th> Name </th>
      <th> Skills </th>
      <th> Profile </th>
    </tr>
    <% @job.job_seekers.each do |job_seeker| %>
      <tr>
        <td><%= job_seeker.name %></td>
        <td><%= job_seeker.skills.collect(&:name).join(", ") %></td>
        <td><%= link_to job_seeker.name, job_seeker %></td>
        <td><%= link_to "Resume", job_seeker.resume.url %></td>
      </tr>
    <% end %>
  </table>
  <% end %>
  <%= link_to 'Back to profile', eprofile_path %>
</fieldset>