config/routes.rb
JobsJugaad::Application.routes.draw do

  resources :job_seekers, :controller => "job_seekers", :except => [:new]
  controller 'job_seekers' do
    get "profile" => :profile
    get "register" => :new
    get "remove_photo" => :remove_photo
  end
  resources :employers, :controller => "employers", :except => [:new]
  controller 'employers' do
    get "elogin" => :login
    get "eregister" => :new
    get "eprofile" => :profile
    get "add_job" => :add_job
    get "remove_photo_emp" => :remove_photo
  end
  resources :jobs
  controller :jobs do
    get "view_applicants" => :view_applicants
    post "search_results" => :search_results
    get "search_results" => :search_results
    post "apply" => :apply
  end
  resources :sessions, :except => [:destroy]
  controller :sessions do
    get "logout" => :destroy
    post "login" => :login
    post "eregister" => :register
    post "register" => :register
    get "change_password" => :change_password
    post "update_password" => :update_password
    get "forgot_password" => :forgot_password
    post "reset_password" => :reset_password
    get "set_new_password" => :set_new_password
    get "reset_user_password" => :reset_user_password
    get "activate_user" => :activate_user
    post "set_new_password" => :set_new_password
    post "save_new_password" => :save_new_password
  end

  root :to => 'home#index'

end

app/models/employer.rb
class Employer < ActiveRecord::Base
  attr_accessible :name, :email, :website, :description, 
                  :password, :password_confirmation, :photo,
                  :auth_token, :activated, :password_reset_token
  has_many :jobs, :dependent => :destroy
  has_secure_password
  validates :name, :presence  => true
  validates :email, :presence => true, :uniqueness => true
  validates :password, :confirmation => true, :presence => true, :if => :password
  validates :password_confirmation, :presence => true, :if => :password 
  validates :password, :length => { :minimum => 6 }, :if => :password
  
  validates_format_of :email,
    :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i,
    :message => "Doesn't Looks the correct email ID"

  validates :website, :presence => true
  validates_format_of :website, 
    :with    => /^(https?:\/\/)?((([A-z]+)\.)*)([A-z]+\.[A-z]{2,4})$/,
    :message => "Doesn't looks like correct Website URL" 

  has_attached_file :photo, :styles => { :small => "175x175>"}, :default_url => '/assets/default-photo/default.gif'

  validates_attachment_size :photo, :less_than => 6.megabytes
  validates_format_of :photo, :with => %r{\.(jpg|jpeg|png|ico|gif)}i, :message => "Invalid Image: Allowed Formats Are Only in jpeg, jpg, png, ico and gif"
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController

  before_filter :is_valid_access?, :except => [:new, :forgot_password, :show, :login]

  def is_valid_access?
    if session[:id].nil? 
      redirect_to root_path , :notice => "You are not currently logged into the system..."      
    end
  end

  def employer_authorised_to_see_profile?
    authorized_ids = get_authorized_ids
    @employer = Employer.find(session[:id])
    @employer.jobs.each do |job|
      authorized_ids.concat(job.job_seekers.collect(&:id))
    end

    if(authorized_ids.include?(Integer(params["id"])))
      return true
    else 
      return false
    end
  end

  def get_authorized_ids
    authorized_ids = []
    @employer = Employer.find(session[:id])
    @employer.jobs.each do |job|
      authorized_ids.concat(job.job_seekers.collect(&:id))
    end
    authorized_ids
  end

  def profile
    @employer = Employer.find(session[:id])
  end
  
  def edit
    if params[:id].to_s == session[:id].to_s
      @employer = Employer.find(params[:id])
    else
      redirect_to :eprofile, :notice => "You are not authorised to edit this profile"
    end
  end

  def show
    @employer = Employer.find(params[:id])
  end

  def update
    @employer = Employer.find(params[:id])

    respond_to do |format|
      if @employer.update_attributes(params[:employer])
        format.html { redirect_to eprofile_url, notice: "Employer Profile was successfully updated." }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def remove_photo
    @employer = Employer.find(session[:id])
    @employer.photo.destroy
    @employer.update_attribute(:photo, nil)
    redirect_to eprofile_path
  end

  def new
    @employer = Employer.new
  end

  def add_job
    @employer = Employer.find(session[:id])
    @job = @employer.jobs.build
  end

end

app/helpers/employers_helper.rb
module EmployersHelper

end

app/views/employers/add_job.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited the details from being saved:</h2>
    </div>
  <% end %>    
  <fieldset>
    <% unless notice.nil? %>
      <div id = "notice"> <%= notice %> </div>
    <% end %>
    <legend>Adding New Job</legend>
    <table>
      <tr>
        <td><%= f.label "Job Title" %></td>
        <td><%= f.text_field :title %></td>
      </tr>
      <tr>
        <td><%= f.label "Job Description" %></td>
        <td><%= f.text_area :description %></td>
        <% unless error_present?(:description, @job) %>
          <td class="error-notice"><%= get_errors(:description, @job) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= f.label :location %></td>
        <td><%= f.text_field :location %></td>
        <% unless error_present?(:location, @job) %>
          <td class="error-notice"><%= get_errors(:location, @job) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= f.label :key_skills %></td>
        <td><%= f.text_field :key_skills %></td>
      </tr>
      <tr>
        <td><%= f.label "Salary" %></td>
        <td>
          <%= f.text_field :salary_min, :class => "salary-fields", :placeholder => "Minimum Salary" %> to 
          <%= f.text_field :salary_max, :class => "salary-fields", :placeholder => "Maximum Salary" %>
        </td>
        <% unless error_present?(:salary_min, @job) && error_present?(:salary_max, @job) %>
          <td class="error-notice">
            <%= get_errors(:salary_min, @job)%> <br /> 
            <%= (get_errors(:salary_max, @job)) %>
          </td>
        <% end %>
      </tr>
      <tr>
        <td></td><td>
          <%= f.select :salary_type, [["LPA", "LPA"], ["pm", "pm"]], :prompt => "Salary Type" %>
        </td>
        <% unless error_present?(:salary_type, @job) %>
          <td class="error-notice"><%= get_errors(:salary_type, @job) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= f.submit %></td>
      </tr>
    </table>
    <%= link_to 'Back to Profile', eprofile_path %>
  </fieldset>
<% end %>

app/views/employers/edit.html.erb
<%= form_for(@employer) do |post_form| %>
  <% if @employer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employer.errors.count, "error") %> prohibited the details from being saved:</h2>
    </div>
  <% end %>
  
  <fieldset><legend>Editing Profile</legend>
  <div id="form">
      <table id="edit_table">
        <tr>
          <td><%= post_form.label :name %></td>
          <td><%= post_form.text_field :name %></td>
            <% str = "" %>
            <% unless error_present?(:name, @employer) %>
              <td class="error_notice"><%= get_errors(:name, @employer) %></td>
            <% end %>
        </tr>
        <tr>
          <td><%= post_form.label :email %></td>
          <td><%= @employer.email %></td>
        </tr>
        <tr>
          <td><%= post_form.label :website %></td>
          <td><%= post_form.url_field :website %></td>
        </tr>
        <tr>
          <td><%= post_form.label :description %></td>
          <td><%= post_form.text_area :description %></td>
        </tr>
        <tr>
          <td>Profile Image: </td>
          <td><%= post_form.file_field :photo %></td>
        </tr>
        <tr>
          <td><%= post_form.submit %></td>
      </table>
    <%= link_to 'Back to Profile', profile_path %>
  </div>
  </fieldset>
<% end %>

app/views/employers/login.html.erb
<% unless session[:id].nil? %>
  <br /><br />
  <div id="logged-in">
    <p> You are Already Logged in </p>
  </div>
<% else %>
  <fieldset>
    <legend>Login As Employer</legend>
    <div id="login">
      <% if notice %>
        <div id="notice"><p><%= notice %></p></div>
      <% end %>
      <%= form_tag(:controller => "sessions", :action => "login") do %>
        <table>
          <tr>
            <td><%= label_tag :email, "Enter Email" %></td>
            <td><%= email_field :email, params[:email] %></td>
          </tr>
          <tr>
            <td><%= label_tag :password, "Enter Password" %></td>
            <td><%= password_field_tag :password %></td>
          </tr>
          <tr>
            <td><%= hidden_field_tag :user_type, "employer" %></td>
          </tr>
          <tr>
            <td></td><td><%= submit_tag "Login" %></td>
          </tr>
        </table>
        <%= link_to 'Forgot Password', forgot_password_path(:user => "Employer") %>
        <%= link_to 'Register New', eregister_path %>
      <% end %>
  </fieldset>
<% end %>

app/views/employers/new.html.erb
<%= form_for(@employer, :url => { :controller => "sessions", :action => "register" }) do |f| %>
  <% if @employer.errors.any? %>
    <div class="error_messages">
     <h2><%= pluralize(@employer.errors.count, "error") %> prohibited the details from being saved:</h2>
    </div>
  <% end %>
  <fieldset>
    <legend>Registration</legend>
    <table>
      <tr>
        <td><%= f.label :name %></td>
        <td><%= f.text_field :name %></td>
        <% unless error_present?(:name, @employer) %>
          <td class="error-notice"><%= get_errors(:name, @employer) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= f.label :email %></td>
        <td><%= f.email_field :email %></td>
        <% unless error_present?(:email, @employer) %>
          <td class="error-notice"><%= get_errors(:email, @employer) %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= f.label :password %></td>
        <td><%= f.password_field :password %></td>
        <% unless error_present?(:password, @employer) %>
          <td class="error-notice"><%= get_errors(:password, @employer) %></td>
        <% end %>
        </tr>
      <tr>
        <td><%= f.label :password_confirmation %></td>
        <td><%= f.password_field :password_confirmation %></td>
        <% unless error_present?(:password_confirmation, @employer) %>
          <td class="error-notice"><%= get_errors(:password_confirmation, @employer) %></td>
        <% end %>
        </tr>
      <tr>
        <td><%= f.label :website %></td>
        <td><%= f.url_field :website %></td>
        <% unless error_present?(:website, @employer) %>
          <td class="error-notice"><%= get_errors(:website, @employer) %></td>
        <% end %>
        </tr>
      <tr>
        <td><%= f.label :description %></td>
        <td><%= f.text_area :description, :rows => 10 %></td>
      </tr>
      <tr>
        <td></td>
        <td><p class="button"><%= f.submit %></p></td>
      </tr>
    </table>
    <%= link_to 'Back to Login', elogin_path %>
  </fieldset>
<% end %>

app/views/employers/profile.html.erb
<% if session[:id].nil? || session['user_type'] != 'employer' %>
  <center>
    <div id="not_login">
    <p>
      You are not currently logged into the system...
      <br />Please click <%= link_to 'here', elogin_path %> to login
    </p>
    </div>
  </center>
<% else %>
  <br />
  <br />
  <div id = "main-container">
    <h3> Welcome <%= @employer.name %></h3>
    <fieldset class="profile-fieldset" id="profile-info">
      <legend id="profile-info-legend">Your Profile Information</legend>
      <% unless notice.nil? %>
        <div id = "notice"> <%= notice %> </div>
      <% end %>
      <div id="profile-container">
        <div id="links_to_use">
          <%= link_to 'Change Password', change_password_path %> | 
          <%= link_to 'Edit', edit_employer_path(@employer) %>
        </div>
        <div id = "profile_div">
        <h5> Your Profile Information : </h5>
        <div id = "profile-image">
         <%= image_tag @employer.photo.url(:small) %>
          <ul>
            <li><%= link_to 'Change Image', "" %></li>
            <li><%= link_to 'Remove Image', remove_photo_emp_path %></li>
          </ul>
        </div>
        <div id="profile_table">
          <table>
            <tr><td> Name:   </td><td><%= @employer.name %></td></tr>
            <tr><td> Email:  </td><td><%= @employer.email %></td></tr>
            <tr><td> Website:</td><td><%= link_to @employer.website, @employer.website %></td></tr>
            <tr><td> Description: </td><td><%= @employer.description %></td></tr> 
          </table>
        </div>
      </div>
    </fieldset>
    <fieldset class="profile-fieldset"><legend>Your Job Postings...</legend>
      <table>
        <% @employer.jobs.each do |job| %>
            <tr>
              <td> Job # <%= @employer.jobs.index(job) + 1 %></td>
              <td>
                <%= link_to 'Show', job %>
                <%= link_to 'Edit', edit_job_path(job) %> 
                <%= link_to 'Delete Job', job, :method => :delete, :confirm => "Are You Sure to delete this job?" %>
                <%= link_to 'View Applicants', view_applicants_path(:id => job.id) %>
              </td>
              </tr>
            <tr><td> Job Description : </td><td> <%= job.description %></td></tr>
            
        <% end %>
      </table>
      <%= link_to "Post a New Job", add_job_path %>
    </fieldset>
    <fieldset class="profile-fieldset">
      <legend>Search For Talent</legend>
      <%= form_tag %>
    </fieldset>
  </div>
<% end %> 

app/views/employers/show.html.erb
  <div id = "main-container">
    <fieldset>
      <legend>Employer Profile Information</legend>
      <% unless notice.nil? %>
        <div id = "notice"> <%= notice %> </div>
      <% end %>
      <div id="profile-container">
        <div id = "profile_div">
        <h5> Employer Profile Information : </h5>
        <div id = "profile-image">
         <%= image_tag @employer.photo.url(:small) %>
        </div>
        <div id="profile_table">
          <table>
            <tr><td> Name:   </td><td><%= @employer.name %></td></tr>
            <tr><td> Website:</td><td><%= link_to @employer.website, @employer.website %></td></tr>
            <tr><td> Description: </td><td><%= @employer.description %></td></tr> 
          </table>
        </div>
      </div>
    </fieldset>
    <fieldset>
      <legend>Total Jobs Posted by <%= @employer.name.capitalize %></legend>
      <table>
        <tr>
          <th> Job Title </th>
          <th> Description </th>
          <th> Posted On: </th>
        </tr>
        <% @employer.jobs.each do |job| %>
          <tr>
            <td> <%= link_to job.title, job, :target => "_blank" %></td>
            <td> <%= job.description %></td>
            <td> <%= job.created_at.strftime("%d-%m-%Y") %></td>
            <td> <%= link_to "Apply to the job", "" %></td>
          </tr>
        <% end %>
      </table>
    </fieldset> 
  </div>